---
# Per environment values which override defaults in dv-frontend-app-dev/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: dv-frontend-app-dev-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://dv-frontend-app-dev-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
  
  allowlist:
    sscl-blackpool: sscl-blackpool-pre-prod
    sscl-azure: sscl-azure-pre-prod
    sscl-york: sscl-york- pre-prod
    sscl-newcastle: sscl-newcastle-pre-prod
    sscl-newport: sscl-newport-pre-prod
    groups:
    - internal
    - prisons
    - private_prisons
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
