---
# Per environment values which override defaults in dv-frontend-app-dev/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: dv-frontend-app-dev-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://dv-frontend-app-dev-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
  
  allowlist:
    sscl-blackpool: sscl-blackpool-dev
    sscl-azure: sscl-azure-dev
    sscl-york: sscl-york-dev
    sscl-newcastle: sscl-newcastle-dev
    sscl-newport: sscl-newport-dev
    groups:
    - internal
    - prisons
    - private_prisons
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
